using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HyperQ.Util
{
    [Serializable]
    public class QOrdinalActionSpace : QActionSpace<int>
    {
        private int _KnownActions = 0;
        private int _MaxActions = 0;
        public QOrdinalActionSpace(QRandom ran, int maxActions) : base(ran)
        {
            _MaxActions = maxActions;
        }

        /// <summary>
        /// Returns true if the action is known in this space, and false otherwise.
        /// </summary>
        /// <param name="action">The action, in action space</param>
        /// <returns>true or false</returns>
        public override bool IsKnownAction(int action)
        {
            return (action <= _KnownActions);
        }

        /// <summary>
        /// Clones the contents of this instance into a new one and returns it.
        /// </summary>
        /// <returns></returns>
        public override QActionSpace<int> Clone()
        {
            QOrdinalActionSpace a = new QOrdinalActionSpace(Random, _MaxActions);
            a._KnownActions = _KnownActions;
            return (a);
        }
        /// <summary>
        /// Returns the number of known actions which is just the maximum action that has
        /// been generated by the random action generator
        /// </summary>
        public override uint NumberOfKnownActions
        {
            get
            {
                return (uint)_KnownActions;
            }
        }
        /// <summary>
        /// Returns the maximum number of actions in this space.
        /// </summary>
        public override uint MaximumNumberOfActions
        {
            get {
                return (uint)_MaxActions;
            }
        }

        /// <summary>
        /// Creates an unknown random action in action space
        /// </summary>
        /// <returns></returns>
        public override int UnknownRandomAction()
        {
            return Random.Ran.Next(_MaxActions);
        }
        /// <summary>
        /// Returns a random action and updates the known actions
        /// </summary>
        /// <param name="includeUnknowns"></param>
        /// <returns></returns>
        public override int RandomAction(bool includeUnknowns = true)
        {
            int a = -1;
            if (includeUnknowns)
            {
                a = UnknownRandomAction();
            }
            else
                a = Random.Ran.Next(_KnownActions+1);
            _KnownActions = Math.Max(_KnownActions, a);
            return a;
        }
        /// <summary>
        /// Returns the action space "action" from the given mapped index
        /// </summary>
        /// <param name="index">The mapped index of the action</param>
        /// <returns></returns>
        public override int FromIndex(uint index)
        {
            return (int) index;
        }
        /// <summary>
        /// Returns the mapped index for the given action space "action"
        /// </summary>
        /// <param name="action">The action, in action space</param>
        /// <returns></returns>
        public override uint ToIndex(int action)
        {
            return (uint)action;
        }
    }
}
